services:
  backend:
    build:
      context: ./backend
    container_name: fastapi_backend
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - database
    environment:
      MONGODB_HOST: ${MONGODB_HOST:-database}
      MONGODB_PORT: ${MONGODB_PORT:-27017}
      MONGODB_DATABASE: ${MONGODB_NAME:-myDatabase}

  frontend:
    build:
      context: ./frontend
    container_name: vuejs_frontend
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - backend

  database:
    image: mongo:7.0.12
    container_name: mongodb
    restart: always
    user: mongodb
    volumes:
      - ./data/db:/data/db
    ports:
      - "27017:27017"
    command: mongod --noauth